---
abstract: 'Class for scpn-simulator application.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.18'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SCPN-Simulator
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  English: 0
  File::Temp: 0
  Getopt::Std: 0
  Mojo::Exception: 0
  SCPN::Engine::Simple: 0
  SCPN::Schema::GraphViz: 0
  Tk: 0
  Tk::PNG: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-SCPN-Simulator
  homepage: https://github.com/tupinek/App-SCPN-Simulator
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/App-SCPN-Simulator
version: '0.01'
